/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javaapplication1.login.pname;
/**
 *
 * @author dhees
 */
public class seat extends javax.swing.JFrame {
    public static String seats[]=new String[32];
    /**
     * Creates new form seat
     */
    public seat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        t6 = new javax.swing.JCheckBox();
        t5 = new javax.swing.JCheckBox();
        t3 = new javax.swing.JCheckBox();
        t4 = new javax.swing.JCheckBox();
        t8 = new javax.swing.JCheckBox();
        t7 = new javax.swing.JCheckBox();
        t9 = new javax.swing.JCheckBox();
        t10 = new javax.swing.JCheckBox();
        t1 = new javax.swing.JCheckBox();
        t2 = new javax.swing.JCheckBox();
        t11 = new javax.swing.JCheckBox();
        t12 = new javax.swing.JCheckBox();
        t16 = new javax.swing.JCheckBox();
        t15 = new javax.swing.JCheckBox();
        t13 = new javax.swing.JCheckBox();
        t14 = new javax.swing.JCheckBox();
        t17 = new javax.swing.JCheckBox();
        t18 = new javax.swing.JCheckBox();
        t20 = new javax.swing.JCheckBox();
        t19 = new javax.swing.JCheckBox();
        t21 = new javax.swing.JCheckBox();
        t22 = new javax.swing.JCheckBox();
        t24 = new javax.swing.JCheckBox();
        t23 = new javax.swing.JCheckBox();
        t25 = new javax.swing.JCheckBox();
        t26 = new javax.swing.JCheckBox();
        t28 = new javax.swing.JCheckBox();
        t27 = new javax.swing.JCheckBox();
        t29 = new javax.swing.JCheckBox();
        t30 = new javax.swing.JCheckBox();
        t32 = new javax.swing.JCheckBox();
        t31 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        busno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setText("Driver");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 50, 43, 18));
        jPanel2.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 99, -1, -1));
        jPanel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 99, -1, -1));
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 75, -1, -1));
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 75, -1, -1));
        jPanel2.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 96, -1, -1));
        jPanel2.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 96, -1, -1));
        jPanel2.add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 123, -1, -1));
        jPanel2.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 123, -1, -1));

        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t1.setMaximumSize(new java.awt.Dimension(30, 30));
        t1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 75, 20, 20));
        jPanel2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 75, -1, -1));
        jPanel2.add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 120, -1, -1));
        jPanel2.add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 120, -1, -1));
        jPanel2.add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 143, -1, -1));
        jPanel2.add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 143, -1, -1));
        jPanel2.add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 144, -1, -1));
        jPanel2.add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 144, -1, -1));

        t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t17ActionPerformed(evt);
            }
        });
        jPanel2.add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 165, -1, -1));
        jPanel2.add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 165, -1, -1));
        jPanel2.add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 165, -1, -1));
        jPanel2.add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 165, -1, -1));
        jPanel2.add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 186, -1, -1));
        jPanel2.add(t22, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 186, -1, -1));
        jPanel2.add(t24, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 185, -1, -1));
        jPanel2.add(t23, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 185, -1, -1));
        jPanel2.add(t25, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 207, -1, -1));
        jPanel2.add(t26, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 207, -1, -1));
        jPanel2.add(t28, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 205, -1, -1));
        jPanel2.add(t27, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 205, -1, -1));
        jPanel2.add(t29, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 228, -1, -1));
        jPanel2.add(t30, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 228, -1, -1));
        jPanel2.add(t32, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 226, -1, -1));
        jPanel2.add(t31, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 226, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setText("BUS NO:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, -1, -1));

        busno.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        busno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busnoActionPerformed(evt);
            }
        });
        jPanel2.add(busno, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 11, 61, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("CONFIRM ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 267, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 200, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhees\\Downloads\\ash-gerlach-6fF-Ojxov6o-unsplash.jpg")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus", "root", "3117@d");
            Statement stmt = conn.createStatement();
            String bn=busno.getText();
            String seat="";
            int i=0;
            if(t1.isSelected()){
                seat="1";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);
                seats[i]=seat;i++;}
            if(t2.isSelected()){
                seat="2";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t3.isSelected()){
                seat="3";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t4.isSelected()){
                seat="4";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t5.isSelected()){
                seat="5";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t6.isSelected()){
                seat="6";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t7.isSelected()){
                seat="7";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t8.isSelected()){
                seat="8";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t9.isSelected()){
                seat="9";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t10.isSelected()){
                seat="10";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t11.isSelected()){
                seat="11";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t12.isSelected()){
                seat="12";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t13.isSelected()){
                seat="13";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t14.isSelected()){
                seat="14";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t15.isSelected()){
                seat="15";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t16.isSelected()){
                seat="16";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t17.isSelected()){
                seat="17";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t18.isSelected()){
                seat="18";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t19.isSelected()){
                seat="19";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t20.isSelected()){
                seat="20";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t21.isSelected()){
                seat="21";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t22.isSelected()){
                seat="22";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t23.isSelected()){
                seat="23";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t24.isSelected()){
                seat="24";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t25.isSelected()){
                seat="25";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t26.isSelected()){
                seat="26";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t27.isSelected()){
                seat="27";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t28.isSelected()){
                seat="28";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t29.isSelected()){
                seat="29";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t30.isSelected()){
                seat="30";String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t31.isSelected()){
                seat="31";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"' where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            if(t32.isSelected()){
                seat="32";
                String sql1="update ticket set t_status='Booked',username='"+ pname +"'  where seat_num='"+seat+"' and busno='"+bn+"'";
                stmt.executeUpdate(sql1);seats[i]=seat;i++;}
            PreparedStatement query=conn.prepareStatement("select tic_price from busdetails where busno='"+bn+"'");
            ResultSet r= query.executeQuery();
            double p=0;
            while(r.next())
            p=r.getDouble("tic_price");
            p=p*i;
            String pay="PAY RS "+p;
            JOptionPane.showMessageDialog(this, pay);
            user ob=new user();
            ob.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(seat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void busnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busnoActionPerformed

    private void t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seat().setVisible(true);
            }
        });
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus", "root", "3117@d"); 
            //Statement stmt = conn.createStatement();
            String bn=book.mn;
            PreparedStatement sql= conn.prepareStatement("select seat_num from ticket where busno='"+bn+"' and t_status='Booked'");
            ResultSet rs = sql.executeQuery();
            String sn1[]=new String[32];
            int i=0;
            while(rs.next()){
                String sn=rs.getString("seat_num");
                sn1[i]=sn;
                i++;
            }
            for (int j=0;j<i;j++) {
                if (sn1[j].equals("1")) {
                    t1.setVisible(false);
                }
                if (sn1[j].equals("2")) {
                    t2.setVisible(false);
                }
                if (sn1[j].equals("3")) {
                    t3.setVisible(false);
                }
                if (sn1[j].equals("4")) {
                    t4.setVisible(false);
                }
                if (sn1[j].equals("5")) {
                    t5.setVisible(false);
                }
                if (sn1[j].equals("6")) {
                    t6.setVisible(false);
                }
                if (sn1[j].equals("7")) {
                    t7.setVisible(false);
                }
                if (sn1[j].equals("8")) {
                    t8.setVisible(false);
                }
                if (sn1[j].equals("9")) {
                    t9.setVisible(false);
                }
                if (sn1[j].equals("10")) {
                    t10.setVisible(false);
                }
                if (sn1[j].equals("11")) {
                    t11.setVisible(false);
                }
                if (sn1[j].equals("12")) {
                    t12.setVisible(false);
                }
                if (sn1[j].equals("13")) {
                    t13.setVisible(false);
                }
                if (sn1[j].equals("14")) {
                    t14.setVisible(false);
                }
                if (sn1[j].equals("15")) {
                    t15.setVisible(false);
                }
                if (sn1[j].equals("16")) {
                    t16.setVisible(false);
                }
                if (sn1[j].equals("17")) {
                    t17.setVisible(false);
                }
                if (sn1[j].equals("18")) {
                    t18.setVisible(false);
                }
                if (sn1[j].equals("19")) {
                    t19.setVisible(false);
                }
                if (sn1[j].equals("20")) {
                    t20.setVisible(false);
                }
                if (sn1[j].equals("21")) {
                    t21.setVisible(false);
                }
                if (sn1[j].equals("22")) {
                    t22.setVisible(false);
                }
                if (sn1[j].equals("23")) {
                    t23.setVisible(false);
                }
                if (sn1[j].equals("24")) {
                    t24.setVisible(false);
                }
                if (sn1[j].equals("25")) {
                    t25.setVisible(false);
                }
                if (sn1[j].equals("26")) {
                    t26.setVisible(false);
                }
                if (sn1[j].equals("27")) {
                    t27.setVisible(false);
                }
                if (sn1[j].equals("28")) {
                    t28.setVisible(false);
                }
                if (sn1[j].equals("29")) {
                    t29.setVisible(false);
                }
                if (sn1[j].equals("30")) {
                    t30.setVisible(false);
                }
                if (sn1[j].equals("31")) {
                    t31.setVisible(false);
                }
                if (sn1[j].equals("32")) {
                    t32.setVisible(false);
                }
            }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }   catch (SQLException ex) {
            Logger.getLogger(seat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField busno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JCheckBox t1;
    public static javax.swing.JCheckBox t10;
    public static javax.swing.JCheckBox t11;
    public static javax.swing.JCheckBox t12;
    public static javax.swing.JCheckBox t13;
    public static javax.swing.JCheckBox t14;
    public static javax.swing.JCheckBox t15;
    public static javax.swing.JCheckBox t16;
    public static javax.swing.JCheckBox t17;
    public static javax.swing.JCheckBox t18;
    public static javax.swing.JCheckBox t19;
    public static javax.swing.JCheckBox t2;
    public static javax.swing.JCheckBox t20;
    public static javax.swing.JCheckBox t21;
    public static javax.swing.JCheckBox t22;
    public static javax.swing.JCheckBox t23;
    public static javax.swing.JCheckBox t24;
    public static javax.swing.JCheckBox t25;
    public static javax.swing.JCheckBox t26;
    public static javax.swing.JCheckBox t27;
    public static javax.swing.JCheckBox t28;
    public static javax.swing.JCheckBox t29;
    public static javax.swing.JCheckBox t3;
    public static javax.swing.JCheckBox t30;
    public static javax.swing.JCheckBox t31;
    public static javax.swing.JCheckBox t32;
    public static javax.swing.JCheckBox t4;
    public static javax.swing.JCheckBox t5;
    public static javax.swing.JCheckBox t6;
    public static javax.swing.JCheckBox t7;
    public static javax.swing.JCheckBox t8;
    public static javax.swing.JCheckBox t9;
    // End of variables declaration//GEN-END:variables
}
